#!/bin/bash

[ -n "$HOTROD_DEBUG" ] && {
  set -x
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
STARTTIME=$(date +%s)
cd $DIR

usage() {
    echo "Usage:"
    echo "hotrodctl start"
    echo "hotrodctl stop"
    echo "hotrodctl restart SERVICENAME"
    echo "hotrodctl enter SERVICENAME"
    exit 1
}

COMMAND=$1

[ $# -gt 0 ] || usage

shift 1

[ -n "$SERVER_VERSION" ] && {

#Install Docker
VERSION=$(apt-cache policy docker-engine | grep Installed | awk '{ print $2; }')
echo $VERSION | grep $SERVER_VERSION 1>/dev/null

[ $? != 0 ] && {
  echo "Updating Docker"
  apt-get update
  CANDIDATE=$(apt-cache policy docker-engine | grep $SERVER_VERSION | grep -v ':' | awk '{ print $1; }')
  apt-get install -y docker-engine=$CANDIDATE
}

}

declare -a RUNLEVELS=("core" "0" "1" "2")

supervise() {
  set -e
  
  while true; do
    
    for runlevel in ${RUNLEVELS[@]}; do
      CANDIDATES=$(docker ps -a -q --format '{{.Names}}' --filter status=exited --filter label=za.co.panoptix.hotrod.projectname=$HOTROD_PROJNAME --filter label=za.co.panoptix.hotrod.startorder=$runlevel)
      [ -n "$CANDIDATES" ] &&  {
        echo "Start hotrod containers runlevel $runlevel..."
        docker start $CANDIDATES 
      }
    done
    sleep 30
    
  done
}

stopall() {
  CANDIDATES=$(docker ps -q --filter status=running --format '{{.Names}}' --filter label=za.co.panoptix.hotrod.projectname=$HOTROD_PROJNAME --filter name=_hotrodctl_)
  [ -n "$CANDIDATES" ] &&  {
    echo 'Stop hotrodctl...'
    timeout 10 docker stop --time=5 $CANDIDATES 
    docker stop --time=5 $CANDIDATES
  }
  CANDIDATES=$(docker ps -q --filter status=running --format '{{.Names}}' --filter label=za.co.panoptix.hotrod.projectname=$HOTROD_PROJNAME)
  [ -n "$CANDIDATES" ] &&  {
    echo 'Stop hotrod containers...'
    docker stop --time=45 $CANDIDATES 
  }
}

svcrestart() {
  CONTAINER=$1
  CANDIDATES=$(docker ps -q --format '{{.Names}}' --filter label=za.co.panoptix.hotrod.projectname=$HOTROD_PROJNAME --filter name=$CONTAINER)
  [ -n "$CANDIDATES" ] &&  {
    echo 'Restart container...'
    docker restart $CANDIDATES 
  }
}


#Setup hotrodctl
[ -n "$HOTROD_PROJNAME" ] && {
  cp /usr/bin/hotrodctl /usr/local/bin/hotrodctl
}

case "$COMMAND" in
    supervise) 
        supervise
        ;;
    svcstop)
        stopall
        ;;
    svcrestart)
        svcrestart $1
        ;;
    stop)
        HOTROD_PROJNAME=$(echo $(docker info 2>/dev/null | grep za.co.panoptix.HotrodProj | head -1| cut -f2 -d'='))
        CANDIDATES=$(docker images | grep hotrodctl | grep -v hotrodctlkeys | head -1 | awk '{ print $1":"$2; }')
        [ -n "$CANDIDATES" ] && {
          docker run --name stop_cmd_runner --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -e DOCKER_HOST=unix:///var/run/docker.sock -e HOTROD_PROJNAME=$HOTROD_PROJNAME $CANDIDATES svcstop
        }
        ;;
    start)
        echo 'Start hotrodctl...'
        docker start $(docker ps -a -q --format '{{.Names}}' --filter label=za.co.panoptix.hotrod.projectname --filter name=_hotrodctl_)
        ;;   
    restart)
        HOTROD_PROJNAME=$(echo $(docker info 2>/dev/null | grep za.co.panoptix.HotrodProj | head -1 | cut -f2 -d'='))    
        CANDIDATES=$(docker images | grep hotrodctl | grep -v hotrodctlkeys | head -1 | awk '{ print $1":"$2; }')
        [ -n "$CANDIDATES" ] && {
          docker run --name restart_cmd_runner_$1 --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -e HOTROD_PROJNAME=$HOTROD_PROJNAME $CANDIDATES svcrestart $1
        }
        ;;
    enter)
        CONTAINER=$1
        COMMAND=$2
        [ -n "$COMMAND" ] || {
           export INTERACTIVE="-it"
           export COMMAND="bash"
        }
        CANDIDATES=$(docker ps --format '{{.Names}}' --filter status=running --filter label=za.co.panoptix.hotrod.projectname --filter name=$CONTAINER)
        [ -n "$CANDIDATES" ] &&  {
          docker exec $INTERACTIVE $(echo $CANDIDATES | cut -f1 -d' ') "$COMMAND"
        }
        ;;     
    *)
        echo "Unknown hotrodctl command '$COMMAND'" >&2
        usage
        ;;
esac   
